### ISSUE TITLE
Improvement : use the new lookup function

### ISSUE THREAD

**Issue by jschaeff** [saz/puppet-ssh#229]
In the manifests, use the new "lookup" function to get data from hiera.

The "deep merge" strategy does what we expect : 
- common.yaml gets some default sshserver_options values
- overriding it on a node level for instance, just adding or correcting what we want.

https://docs.puppet.com/puppet/4.10/hiera_merging.html#setting-merge-behavior-at-lookup-time

**Comment by jschaeff** [comment]
More about this issue:

For instance, I have a common.yaml config like this:

```yaml
# common.yaml
---
sshserver_options:
  AllowGroups: ['sysadm','ssh']
```

If I want a node to have **one more** group in AllowGroups along with the groups from common.yaml, I would like to do:

```yaml
# nodes/myspecialnode.yaml
---
sshserver_options:
  AllowGroups: ['users']
```

The result is what I expect with the puppet lookup command, along with deep merge option:

```
$ puppet lookup --node styx.univ-brest.fr ssh::server_options --merge deep --merge-hash-arrays
---
AllowGroups:
- sysadm
- ssh
- users
```

Even better, I can configure hiera to do this deepmerge like this:
```yaml
# nodes/myspecialnode.yaml
---
lookup_options:
  ssh::server_options:
    merge:
      strategy: deep
      merge_hash_arrays: true
sshserver_options:
  AllowGroups: ['users']
```

And then go with puppet lookup:

```
$ puppet lookup --node styx.univ-brest.fr ssh::server_options
---
AllowGroups:
- sysadm
- ssh
- users
```

This merging configuration inside of hiera has no effect on this module. It always will use only the values specified in AllowGroups from the higher hiera level.

I hope I'm clear about this, it's a bit tricky to explain.

Thanks,

Jonathan
